name: flutter_locker
description: Plugin that secures your secrets in keychain using biometric authentication.
version: 1.0.0
authors:
  - Josip Krnjic <josip.krnjic@infinum.com>
  - Ivan Dikic <ivan.dikic@infinum.hr>
repository: https://github.com/infinum/flutter-plugins-locker

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  protobuf: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin
