name: flutter_locker
description: Secures your secrets in keychain using biometric authentication (Fingerprint, Touch ID, Face ID...)
version: 2.0.4
repository: https://github.com/infinum/flutter-plugins-locker
homepage: https://github.com/infinum/flutter-plugins-locker

flutter:
  plugin:
    platforms:
      android:
        package: com.infinum.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  pigeon: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11