name: flutter_locker
description: Secures your secrets in keychain using biometric authentication (Fingerprint, Touch ID, Face ID...)
version: 2.0.4
repository: https://github.com/infinum/flutter-plugins-locker
homepage: https://github.com/infinum/flutter-plugins-locker

environment:
  sdk: '>=2.16.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^3.1.2
  build_runner: ^2.1.11

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_locker
        pluginClass: FlutterLockerPlugin
      ios:
        pluginClass: FlutterLockerPlugin
